[dependencies]
cl-traits = "1.0"
rand = { default-features = false, optional = true, version = "0.7" }
rayon = { default-features = false, optional = true, version = "1.0" }
serde = { default-features = false, features = ["derive"], optional = true, version = "1.0" }
staticvec = { default-features = false, optional = true, version = "0.9" }

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"

[features]
alloc = ["cl-traits/alloc", "rand/alloc", "serde/alloc"]
const_generics = ["cl-traits/const_generics"]
default = []
std = ["alloc", "cl-traits/std", "rand/std", "serde/std"]
with_arrayvec = ["cl-traits/with_arrayvec"]
with_rand = ["rand"]
with_rayon = ["rayon", "std"]
with_serde = ["cl-traits/with_serde", "rand/serde1", "serde"]
with_smallvec = ["cl-traits/with_smallvec"]
with_staticvec = ["cl-traits/with_staticvec", "const_generics", "staticvec", "staticvec/serde_support", "staticvec/std"]

[package]
authors = ["Caio Fernandes <c410.f3r@gmail.com>"]
categories = ["data-structures", "concurrency", "science", "no-std"]
description = "Sparse structures for N-dimensions"
edition = "2018"
keywords = ["coo", "csr", "dimension", "sparse", "structure"]
license = "Apache-2.0"
name = "ndsparse"
readme = "README.md"
repository = "https://github.com/c410-f3r/ndsparse/"
version = "0.5.2"

[package.metadata.docs.rs]
all-features = true
