comment_width = 100
edition = "2018"
error_on_line_overflow = true
error_on_unformatted = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
merge_imports = true
tab_spaces = 2
use_field_init_shorthand  = true
use_small_heuristics = "Max"
version = "Two"
wrap_comments = true