[dependencies]
ndsparse = { features = ["alloc"], path = "../ndsparse" }
pyo3 = { features = ["extension-module"], git = "https://github.com/PyO3/pyo3", optional = true }

[features]
with_pyo3 = ["pyo3"]

[lib]
crate-type = ["cdylib"]

[package]
edition = "2018"
name = "ndsparse-bindings"
publish = false
version = "0.0.0"